openapi: 1.0.0
info:
  description:
    JSON Web Service.
  version: "1.0.0-oas3"
  title: JSON Web Service
  termsOfService: ''
  contact:
    email: andriistiawan75@gmail.com
  license:
    name: ''
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Person
    description: Person APIs
    
paths:                    
  /api/v1/person:
    post:
      tags:
        - Person
      summary: Get New Person
      description: ''
      operationId: getNewPerson
      responses:
        '200':
          description: Successfully get Person
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object

components:
  requestBodies:
  parameters:
  securitySchemes:
  responses:
  schemas: