openapi: 1.0.0
info:
  description:
    Contribution System.
  version: "1.0.0-oas3"
  title: Contribution System
  termsOfService: ''
  contact:
    email: anesiput@gmail.com
  license:
    name: ''
servers:
  - url: 'http://localhost:4000'
tags:
  - name: Generator
    description: Generator APIs
  - name: Contributor
    description: Contributor APIs

    
paths:
  /api/v1/generator/register:
    post:
      tags:
        - Generator
      summary: Register Generator baru
      description: ''
      operationId: postNewGenerator
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                token:
                  type: string
                tokenExpires:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Success
                  link:
                    type: string
                    example: http://localhost:4000/api/v1/contributor/185b5828b6a653f7d9858d333327a3a0a0be86b6
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Error
  
  /api/v1/generator/login:
    post:
      tags: 
        - Generator
      summary: Login sebagai Generator existing
      description: ''
      operationId: loginGenerator
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Sukses login
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: string
                    example: admin
                  name:
                    type: string
                    example: admin
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTdlZDFkNGE5MTNmMDc3NGMzNGFmMiIsImVtYWlsIjoic21hcnRleWUuaWRAZ21haWwuY29tIiwiaWF0IjoxNTcxMjg3MDA4fQ.bbQaZVpCCGG_UA2CpR_ywSMT368AWTj7p2fYB3Bm6os
        '400':
          description: Username atau password salah
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username atau password yang anda masukkan salah
                  user:
                    type: string
                    example: admin
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: server bermasalah
                    
  /api/v1/generator/new-link:
    post:
      tags:
        - Generator
      summary: Get New Link
      description: ''
      operationId: getNewLinkGenerator
      security:
        - AuthBearerToken: []
      responses:
        '200':
          description: Successfully retrieve contents
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Success
                  link:
                    type: string
                    example: http://localhost:4000/api/v1/contributor/185b5828b6a653f7d9858d333327a3a0a0be86b6
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                example: Unauthorized
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: server bermasalah
                    
  /api/v1/contributor/:
    post:
      tags:
        - Contributor
      summary: POST New Contributor
      description: ''
      operationId: postNewContributor
      parameters:
      - $ref: '#/components/parameters/tokenParam'
      responses:
        '200':
          description: Successfully add new contribution
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                      type: boolean
                      example: True
                  message:
                    type: string
                    example: Successfully add new contribution
                  contributor:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Contributor'
        '400':
          description: Link tidak Valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Link tidak valid atau telah kedaluwarsa
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: False
                  message:
                    type: string
                    example: Error

components:
  requestBodies:
    GeneratorArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Generator'
      description: List of user object
      required: true
    ContributorArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Contributor'
      description: List of user object
      required: true
  parameters:
    tokenParam:
      name: token
      in: path
      required: true
      schema:
        type: string
        example: ak89asd8a9sd809a8sd0a8dok12jo123kn183
    pageParam:
      in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number that want to be retrieved - default to 1
    perPageParam:
      in: query
      name: perPage
      schema:
        type: integer
        minimum: 1
        default: 10
      description: Number of contents to be displayed per page - default to 10
  securitySchemes:
    AuthBearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Generator:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          example: admin
        email:
          type: string
          example: admin@gmail.com
        password:
          type: string
          example: admin
        token:
          type: string
          example: 185b5828b6a653f7d9858d333327a3a0a0be86b6
        tokenExpires:
          type: string
          example: 12-02-2020
    Contributor:
      type: object
      properties:
        contribution:
          type: integer
          example: 1
        email:
          type: array
          items:
            type: string
          example: ["admin@gmail.com"]
        slug:
          type: string
          example: 185b5828b6a653f7d9858d333327a3a0a0be86b6